[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "Rest.py"
version = "0.0.1"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "pandas",
    "pytest",

]

[tool.setuptools]
package_dir = "src"
packages.find = { where = "src" }

